import {auth,db} from './firebase-config.js';
import {collection,getDocs} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {norm,clean,esc,studentIdOf,rollNoOf,subjectIdOf,attendanceDate,attendanceStudentId,attendanceStatus,attendanceTime,indiaDate,dateRange,dayNameForDate,scheduledForStudent,recordMatchesSession} from './attendix-utils.js';
const $=id=>document.getElementById(id);let students=[],subjects=[],timetable=[],attendance=[];
async function load(){const [s,a,t,sub]=await Promise.all([getDocs(collection(db,'students')),getDocs(collection(db,'attendance')),getDocs(collection(db,'timetable')),getDocs(collection(db,'subjects'))]);students=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);attendance=a.docs.map(d=>({id:d.id,...d.data()}));timetable=t.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);subjects=sub.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);populate();defaults();render();}
function populate(){const e=$('subjectFilter');if(!e)return;e.innerHTML='<option value="">All Subjects</option>';subjects.sort((a,b)=>String(a.name).localeCompare(String(b.name))).forEach(s=>e.insertAdjacentHTML('beforeend',`<option value="${esc(s.id)}">${esc(s.name||s.code||s.id)}</option>`));}
function defaults(){const t=indiaDate();$('startDate')&&($('startDate').value||($('startDate').value=`${t.slice(0,7)}-01`));$('endDate')&&($('endDate').value||($('endDate').value=t));}
function report(s,start,end,subject){const sessions=[];for(const d of dateRange(start,end)){const day=dayNameForDate(d);for(const t of timetable){if(t.active===false||norm(t.day)!==norm(day)||!scheduledForStudent(t,s)||subject&&subjectIdOf(t)!==subject)continue;sessions.push({date:d,t});}}const atts=attendance.filter(a=>attendanceStudentId(a)===studentIdOf(s)&&norm(attendanceStatus(a))==='present'&&(!subject||String(a.subjectId||a.subject_id||a.subjectID||'')===subject)&&attendanceDate(a)>=start&&attendanceDate(a)<=end);const keys=new Set();for(const x of sessions){if(atts.some(a=>recordMatchesSession(a,x.date,x.t)))keys.add(`${x.date}|${x.t.id}`);}const total=sessions.length,present=keys.size,absent=Math.max(total-present,0),pct=total?present*100/total:0;return{student:s,total,present,absent,pct};}
function render(){const start=$('startDate')?.value||'',end=$('endDate')?.value||indiaDate(),subject=clean($('subjectFilter')?.value),status=norm($('statusFilter')?.value),q=norm($('searchInput')?.value);let rows=students.map(s=>report(s,start,end,subject));if(q)rows=rows.filter(r=>`${r.student.name} ${rollNoOf(r.student)} ${r.student.email||''}`.toLowerCase().includes(q));if(status==='good')rows=rows.filter(r=>r.total>0&&r.pct>=75);if(status==='low')rows=rows.filter(r=>r.total>0&&r.pct<75);const withClasses=rows.filter(r=>r.total>0);const avg=withClasses.length?withClasses.reduce((x,r)=>x+r.pct,0)/withClasses.length:0;$('totalStudents')&&($('totalStudents').textContent=rows.length);$('goodAttendance')&&($('goodAttendance').textContent=withClasses.filter(r=>r.pct>=75).length);$('lowAttendance')&&($('lowAttendance').textContent=withClasses.filter(r=>r.pct<75).length);$('averageAttendance')&&($('averageAttendance').textContent=avg.toFixed(1)+'%');const body=$('reportsTableBody');if(body)body.innerHTML=rows.length?rows.sort((a,b)=>String(rollNoOf(a.student)).localeCompare(String(rollNoOf(b.student)),undefined,{numeric:true})).map(r=>`<tr><td>${esc(rollNoOf(r.student)||'—')}</td><td><strong>${esc(r.student.name||'Unknown')}</strong></td><td>${r.total}</td><td>${r.present}</td><td>${r.absent}</td><td>${r.pct.toFixed(1)}%</td><td><span class="badge ${r.total===0?'badge-neutral':r.pct>=75?'badge-good':'badge-low'}">${r.total===0?'No Classes':r.pct>=75?'Good':'Low'}</span></td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;">No students found.</td></tr>';}
['startDate','endDate','subjectFilter','statusFilter','searchInput'].forEach(id=>$(id)?.addEventListener('input',render));
$('csvDownloadBtn')?.addEventListener('click',()=>{const start=$('startDate')?.value,end=$('endDate')?.value,subject=clean($('subjectFilter')?.value);const rows=students.map(s=>report(s,start,end,subject)).map(r=>[rollNoOf(r.student),r.student.name||'',r.total,r.present,r.absent,r.pct.toFixed(1)+'%',r.pct>=75?'Good':'Low']);const csv=['Roll No,Student Name,Total Classes,Present,Absent,Attendance %,Status',...rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download='ATTENDIX_Attendance_Report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
onAuthStateChanged(auth,u=>{if(!u)return;load().catch(e=>console.error(e));});
